/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page
    services: Service
    'service-areas': ServiceArea
    'blog-posts': BlogPost
    testimonials: Testimonial
    media: Media
    users: User
  }
  globals: {
    settings: Settings
  }
}

/**
 * SEO fields used across collections
 */
export interface SEOFields {
  title?: string | null
  description?: string | null
  image?: string | Media | null
  keywords?: string | null
}

/**
 * Open Graph fields
 */
export interface OpenGraphFields {
  ogTitle?: string | null
  ogDescription?: string | null
  ogImage?: string | Media | null
}

/**
 * Meta fields combining SEO and Open Graph
 */
export interface MetaFields {
  seo?: SEOFields
  openGraph?: OpenGraphFields
}

/**
 * Rich text content type
 */
export type RichTextContent = {
  root: {
    type: string
    children: {
      type: string
      version: number
      [k: string]: unknown
    }[]
    direction: ('ltr' | 'rtl') | null
    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
    indent: number
    version: number
  }
  [k: string]: unknown
}

/**
 * Page collection
 */
export interface Page {
  id: string
  title: string
  slug: string
  status: 'draft' | 'published'
  publishedAt?: string | null
  layout?: (HeroBlock | ContentBlock | CTABlock | FeaturedServicesBlock | TestimonialsBlock | FAQBlock)[] | null
  meta?: MetaFields
  updatedAt: string
  createdAt: string
}

/**
 * Hero block for pages
 */
export interface HeroBlock {
  blockType: 'hero'
  heading: string
  subheading?: string | null
  backgroundImage?: string | Media | null
  ctaText?: string | null
  ctaLink?: string | null
  secondaryCtaText?: string | null
  secondaryCtaLink?: string | null
  id?: string | null
}

/**
 * Content block for rich text
 */
export interface ContentBlock {
  blockType: 'content'
  columns?: ('one' | 'two' | 'three') | null
  content?: RichTextContent | null
  id?: string | null
}

/**
 * Call to action block
 */
export interface CTABlock {
  blockType: 'cta'
  heading: string
  description?: string | null
  buttonText: string
  buttonLink: string
  style?: ('primary' | 'secondary') | null
  id?: string | null
}

/**
 * Featured services block
 */
export interface FeaturedServicesBlock {
  blockType: 'featuredServices'
  heading?: string | null
  services?: (string | Service)[] | null
  id?: string | null
}

/**
 * Testimonials block
 */
export interface TestimonialsBlock {
  blockType: 'testimonials'
  heading?: string | null
  testimonials?: (string | Testimonial)[] | null
  id?: string | null
}

/**
 * FAQ block
 */
export interface FAQBlock {
  blockType: 'faq'
  heading?: string | null
  faqs?: {
    question: string
    answer: string
    id?: string | null
  }[] | null
  id?: string | null
}

/**
 * Service collection
 */
export interface Service {
  id: string
  name: string
  slug: string
  description: RichTextContent
  excerpt?: string | null
  image?: string | Media | null
  icon?: string | null
  features?: {
    feature: string
    id?: string | null
  }[] | null
  faqs?: {
    question: string
    answer: string
    id?: string | null
  }[] | null
  relatedServices?: (string | Service)[] | null
  meta?: MetaFields
  status: 'draft' | 'published'
  updatedAt: string
  createdAt: string
}

/**
 * Service Area collection
 */
export interface ServiceArea {
  id: string
  name: string
  slug: string
  description: RichTextContent
  excerpt?: string | null
  image?: string | Media | null
  services?: (string | Service)[] | null
  neighborhoods?: {
    name: string
    id?: string | null
  }[] | null
  meta?: MetaFields
  status: 'draft' | 'published'
  updatedAt: string
  createdAt: string
}

/**
 * Blog Post collection
 */
export interface BlogPost {
  id: string
  title: string
  slug: string
  author?: string | null
  publishedDate?: string | null
  excerpt?: string | null
  content: RichTextContent
  featuredImage?: string | Media | null
  categories?: {
    category: string
    id?: string | null
  }[] | null
  tags?: {
    tag: string
    id?: string | null
  }[] | null
  relatedPosts?: (string | BlogPost)[] | null
  meta?: MetaFields
  status: 'draft' | 'published'
  updatedAt: string
  createdAt: string
}

/**
 * Testimonial collection
 */
export interface Testimonial {
  id: string
  customerName: string
  service?: string | Service | null
  rating: number
  content: string
  date?: string | null
  location?: string | null
  featured?: boolean | null
  status: 'draft' | 'published'
  updatedAt: string
  createdAt: string
}

/**
 * Media collection
 */
export interface Media {
  id: string
  alt: string
  caption?: string | null
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  updatedAt: string
  createdAt: string
}

/**
 * User collection
 */
export interface User {
  id: string
  email: string
  name?: string | null
  role: 'admin' | 'editor'
  updatedAt: string
  createdAt: string
}

/**
 * Settings global
 */
export interface Settings {
  id: string
  siteName: string
  tagline?: string | null
  logo?: string | Media | null
  contact: {
    phone: string
    email: string
    address?: string | null
    city?: string | null
    state?: string | null
    zip?: string | null
  }
  hours?: {
    monday?: string | null
    tuesday?: string | null
    wednesday?: string | null
    thursday?: string | null
    friday?: string | null
    saturday?: string | null
    sunday?: string | null
    emergencyNote?: string | null
  }
  social?: {
    facebook?: string | null
    instagram?: string | null
    twitter?: string | null
    youtube?: string | null
    linkedin?: string | null
    yelp?: string | null
    googleBusiness?: string | null
  }
  seo?: {
    defaultTitle?: string | null
    defaultDescription?: string | null
    defaultImage?: string | Media | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}

/**
 * API response types
 */
export interface PaginatedResponse<T> {
  docs: T[]
  totalDocs: number
  limit: number
  totalPages: number
  page: number
  pagingCounter: number
  hasPrevPage: boolean
  hasNextPage: boolean
  prevPage: number | null
  nextPage: number | null
}

export interface APIError {
  error: {
    code: string
    message: string
    details?: Array<{
      field?: string
      message: string
    }>
  }
}

export interface APISuccessResponse<T> {
  data: T
  meta?: {
    page?: number
    limit?: number
    total?: number
  }
}

/**
 * Blog API specific types
 */
export interface CreateBlogPostInput {
  title: string
  slug?: string
  author?: string
  excerpt?: string
  content: string
  categories?: string[]
  tags?: string[]
  status?: 'draft' | 'published'
  publishedDate?: string
  meta?: {
    title?: string
    description?: string
    keywords?: string
  }
}

export interface BlogPostListItem {
  id: string | number
  title: string
  slug: string
  excerpt?: string | null
  author?: string | null
  publishedDate?: string | null
  featuredImage?: {
    url?: string | null
    alt: string
  } | null
  categories?: string[]
  tags?: string[]
}

export interface BlogPostDetail extends BlogPostListItem {
  content: RichTextContent
  meta?: MetaFields
  relatedPosts?: BlogPostListItem[]
}

/**
 * Schema.org JSON-LD types
 */
export interface LocalBusinessSchema {
  '@context': 'https://schema.org'
  '@type': 'LocalBusiness'
  name: string
  description?: string
  telephone?: string
  email?: string
  address?: {
    '@type': 'PostalAddress'
    streetAddress?: string
    addressLocality?: string
    addressRegion?: string
    postalCode?: string
    addressCountry?: string
  }
  openingHours?: string[]
  sameAs?: string[]
  image?: string
  url?: string
}

export interface ServiceSchema {
  '@context': 'https://schema.org'
  '@type': 'Service'
  name: string
  description?: string
  provider?: {
    '@type': 'LocalBusiness'
    name: string
  }
  areaServed?: string | string[]
  serviceType?: string
}

export interface BlogPostingSchema {
  '@context': 'https://schema.org'
  '@type': 'BlogPosting'
  headline: string
  description?: string
  author?: {
    '@type': 'Person'
    name: string
  }
  datePublished?: string
  dateModified?: string
  image?: string
  publisher?: {
    '@type': 'Organization'
    name: string
    logo?: {
      '@type': 'ImageObject'
      url: string
    }
  }
}

export interface FAQPageSchema {
  '@context': 'https://schema.org'
  '@type': 'FAQPage'
  mainEntity: Array<{
    '@type': 'Question'
    name: string
    acceptedAnswer: {
      '@type': 'Answer'
      text: string
    }
  }>
}
